### ISSUE TITLE
Fail to add event

### ISSUE THREAD

**Issue by leian-ivey** [GordyD/3ree#11]
I get the following error message when adding an event.

Warning: Failed propType: Invalid prop `error` of type `object` supplied to `AsyncBar`, expected `string`. Check the render method of `PulseApp`.

I can EDIT and DELETE events fine. And if I reload after the error message then the event is added to the list and database.

Any help?

**Comment by leian-ivey** [comment]
Error message changed to: 

Error: Invariant Violation: Objects are not valid as a React child (found: Error: Bad Request). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `AsyncBar`.

**Comment by GordyD** [comment]
Sorry for not picking up sooner. I haven't been able to re-create yet. Have you been able to progress past this, or have any updates?

**Comment by GordyD** [comment]
Any updates on this?

**Comment by GordyD** [comment]
No updates on this recently, and unable to re-create and so I am closing the issue.
