### ISSUE TITLE
Example app doesn't respond to socket events.

### ISSUE THREAD

**Issue by JoeMattie** [GordyD/3ree#12]
It seems that the example app only responds to the result of HTTP requests, and not socket events.

With two browser windows open to the app, changes aren't reflected in both until a refresh...

**Comment by GordyD** [comment]
Could your provide any output from your server plus any output found in your browser console please.

**Comment by JoeMattie** [comment]
sure:

```
npm run build-prod:
```

```
> pulse@0.0.2 build-prod /Users/joe/3ree
> webpack

Hash: b5253ab22f30af877fa9
Version: webpack 1.9.13
Time: 2339ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.67 MB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built]
    + 376 hidden modules
```

```
npm run start
```

```
> pulse@0.0.2 start /Users/joe/3ree
> node server.babel.js

Setting up listener...
Listening for changes...
```

Open two browser windows to localhost:3000

Both browsers log something similar to:

```
action SET_USER_ID @ 17:12:43.490
| prev state Object
| action Object
| next state Object
```

I add an event in browser 1, and it succeeds with:

```
action ADD_EVENT_REQUEST @ 17:14:47.083
action ADD_EVENT_SUCCESS @ 17:14:47.144
```

The other browser window, however, shows nothing (and no messages in the console).  If I reload the page, the event will show up.

The server logged it:

```
Change detected { new_val:
   { created: Sat Nov 28 2015 17:17:47 GMT-0900 (AKST),
     id: 'f3cd20dc-b84c-4a6f-8237-779bd85785f5',
     text: 'asdfasdfadsf',
     userId: '10f69690-95a0-11e5-ba92-258ea4e120ba',
     value: 50 },
  old_val: null }
```

However, if I watch the incoming websocket frames, both windows received the event when it happened:

```
42["event-change",{"new_val":{"created":"2015-11-29T02:17:47.133Z","id":"f3cd20dc-b84c-4a6f-8237-779bd85785f5","text":"asdfasdfadsf","userId":"10f69690-95a0-11e5-ba92-258ea4e120ba","value":50},"old_val":null}]
```

**Comment by GordyD** [comment]
Ok. Everything seems to as expected. 

It is to do with this segment from Realtime.js:

```
if (!change.old_val) {
   if (change.new_val.userId !== state.pulseApp.userId) {
      store.dispatch(actions.addEventSuccess(change.new_val));
   }
}
```

If you have just created a new tab, or a new window, then the app will set the _same_ userId, which means results will not propagate to you (it does not currently account for you to be logged in twice in this example app). Instead if you open a new incognito window (if you are using Chrome) or open a different browser and navigate to the URL you should see the results in real time on both screens.

If you wanted you could remove the inner conditional and you'll see the results in both tabs then (although it will appear twice in the tab in which you created the entry currently).

Hope that helps.

**Comment by GordyD** [comment]
I've decided to change the behaviour slightly as on further thought this might be confusing from a UX point of view when wanting to demo the real time functionalities. Please pull recent changes, run `npm install` then run the app again and try to re-create the issue.

**Comment by JoeMattie** [comment]
Yes, this is working in the manner I had expected now.  I'm having a bit of difficulty understanding what benefit RethinkDB's Changefeeds offer to Redux apps.  As I understand it, the database is essentially only being used as a persistence layer for the Redux state.  Changefeeds' big selling point seems to be that you can have a standing query that will dispatch an event (or execute a function or whatever) when the result of the query mutates.  Since Redux is already handling the task of informing the clients of any changes to state, and that state is simply being persisted in RethinkDB, isn't the Changefeed redundant?

I'm sure I'm probably missing something...

**Comment by GordyD** [comment]
Redux does not have cater for building real-time capabilities across clients. Using RethinkDB change feeds + Socket IO allows for synchronisation of content with minimal fuss. 

If you were to visit this app on two different devices, you'd see any changes from other users in real-time. 

You could of course do this without RethinkDB - just sending an event back over SocketIO whenever a server event is received. But as tasks become more complex, and you want to syndicate something less simplistic this is where RethinkDB change feed's becomes incredibly powerful. 

For example, if we changed the application to show from Other Events, which just shows the last 3 events that happened, to Top Events, we could create a change feed by doing the following:

```
r
    .table('pulses')
    .orderBy('score')
    .limit(3)
    .changes()
```

Even if other events are added which don't alter the current top 3, we would not be informed, but as soon as a change occurs that effects the top 3 we are notified. Typically building real-time leaderboards using other real-time technologies is a challenging task. 

Hopefully this helps a bit.
