### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by loremipson** [GordyD/3ree#14]
Hi there,

Is there a trick to get the hot loading to work? I'm getting the hang of this more, but I'm still new to a webpack workflow. I see you have the plugin and the loader should be working, but as I make changes in the app, I'm having to manually rebuild with the `webpack` command.

I'm not really sure how `server.webpack.js` is being utilized either, so I get the feeling that I'm missing something.

Thanks

**Comment by micky2be** [comment]
+1

**Comment by GordyD** [comment]
This is a good point to raise. These files should really should not be part of the repo currently as I have not spent any time focussed on setting up different environments (development, production). 

I am currently on holiday but I'll dedicate some time when I return (5th December) to enabling hot-reloading whilst working in a development environment.

Thanks for your feedback.

**Comment by GordyD** [comment]
Thanks for submitting the PR, really appreciate it. I'll check it out now.
