### ISSUE TITLE
Is Jade Necessary?

### ISSUE THREAD

**Issue by rapind** [GordyD/3ree#16]
Don't get me wrong. I love Jade (and HAML and Slim), but you'll only even be using it for the entry point on the server so it'll never be larger than this:
https://github.com/GordyD/3ree/blob/master/server/views/index.jade

It's not really part of this stack and seems unnecessary to include it just for this one view. Besides you're using JSX (HTML) on the react side, so now you've got multiple syntax for rendering.

Just an opinion though!

**Comment by GordyD** [comment]
Hey. This is a good point, it does seem superfluous upon reflection. I'll swap it out for standard HTML template so that this aspect is simplified and easier to understand for people without Jade knowledge.

Thank you for your input!

**Comment by rapind** [comment]
Awesome. And thanks for putting this together!

**Comment by GordyD** [comment]
Please check out this [PR](https://github.com/GordyD/3ree/pull/21). I chose the `ejs` view template engine to render plain html with the local variables that are passed in via the call to `.render(view, locals)`. 

Let me know your thoughts.

**Comment by GordyD** [comment]
This PR has now been closed. I am going to close this issue but if you notice anything else feel free to open a new one! :)
