### ISSUE TITLE
initialState is not defined in Realtime.js

### ISSUE THREAD

**Issue by eiktyrner** [GordyD/3ree#2]
I've opened two browsers, Firefox and Chromium. When I add a new pulse in one window the other window throws a ReferenceError since initialState is not defined in Realtime.js.

So it seems like it can't sync between users at this time?

**Comment by GordyD** [comment]
Thanks for reporting this. The [fix](https://github.com/GordyD/3ree/commit/16070fd16c77ff080f806a239e44ad215c06343a) to this has been pushed.
