### ISSUE TITLE
not updating between multiple browsers

### ISSUE THREAD

**Issue by Jan-Jan** [GordyD/3ree#28]
To recreate:
- open session in firefox
- add "x1"
- open session in chrome (this will display "x1")
- add "x2"
- switch back to firefox, which does not display "x2"

To get firefox to display "x2" a refresh is required.

These steps can be repeated, the problem persists (ie, not browser specific).

PS. Thank you for the tutorial and the repository. Much appreciated!

**Comment by GordyD** [comment]
Sorry for not picking this up sooner. Have you managed to resolve this issue?

I have tested in Chrome, Safari and Firefox and no issues on master branch.
