### ISSUE TITLE
Having a grandparent directory named 'src' causes bug

### ISSUE THREAD

**Issue by robotate** [GordyD/3ree#33]
When using the docker standard image for node, projects are put into /usr/src/app.  This means that the second babel module (not sure what it is for, actually) covers all of the 3ree directory.  This caused me errors typical of forgetting to exclude /node_modules/.  In my case it seems to be fine to just add /node_modules/ exclusion to the second module, as below.  Since i'm still pretty fuzzy on how this whole stack works(thanks for helping me learn), maybe this isn't a good solution overall, but one way or another the name of the directory grandparents probably shouldn't break it.

The fix for me in webpack.config.js:

``` javascript
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: ['react-hot', 'babel'],
      exclude: /node_modules/,
      include: __dirname
    }, {
      test: /\.js$/,
      loaders: ['babel'],
      exclude: /node_modules/,
      include: path.join(__dirname, '..', '..', 'src')
    }, {
      test: /\.css?$/,
      loaders: ['style', 'raw'],
      include: __dirname
    }]
  }
```

**Comment by GordyD** [comment]
The 2nd (and redundant) loader config entry has now been removed. Can you update  your local repo and let me know if the issue is resolved?

**Comment by robotate** [comment]
Yep that fixed it.  Thanks!
