### ISSUE TITLE
Misc

### ISSUE THREAD

**Issue by turboteddy** [GordyD/3ree#43]
Hi @GordyD ! I loved your blog post on the the [post on the the 3REE Stack](http://blog.workshape.io/the-3ree-stack-react-redux-rethinkdb-express-js/): 

I'm just in the process of installing your stack on a Vagrant VirtualBox, and noted the following: 
- I get a lot of errors and warnings when running `npm install`. Some of the dependencies seem to be deprecated etc. 
- For convenience, perhaps consider making a Vagrant provision / box?

Keep up the good work!

**Comment by GordyD** [comment]
Apologies, just saw this. I'm planning some housekeeping tasks on this project today so I'll be sure to check installation and dependencies issues.

**Comment by GordyD** [comment]
I've just updated dependencies, refactored any code due to breaking changes/API changes and tested whilst using Node v6.0.0 with RethinkDB 2.3.1. Hopefully this helps with the issues you were experiencing whilst using Vagrant.

**Comment by turboteddy** [comment]
Great! I look forward to giving it a new try!
