### ISSUE TITLE
Error running project  on Windows

### ISSUE THREAD

**Issue by shushiej** [GordyD/3ree#46]
I have cloned this project, and followed the steps accordingly, I have installed rethinkdb on my windows machine. I am using node v6.2.0. 

However when i run npm run start, and go to localhost:3001, i keep getting a 502 Bad Gateway error. 
im not sure why that it. Any suggestions?

**Comment by GordyD** [comment]
I've never personally tested it out on a Windows machine before, however one of the other issues currently open mentions how to get it up and running on it (See: https://github.com/GordyD/3ree/issues/45).  The issue regarding starting the app is around the fact I assume you are running on a Linux based machine with some form of Bash/Shell support (apparently coming to Windows in v10).

To work around this issue try changing the `start` command in `package.json` from:

`NODE_ENV=development node server.babel.js & node server.webpack.js`

to:

`set NODE_ENV=development && start node server.babel.js && node server.webpack.js`

**Comment by shushiej** [comment]
Thank you for the quick reply,
Yeah i tried the package.json change,and currently this displays:

![log](https://cloud.githubusercontent.com/assets/4348935/15659680/e9e646b2-2722-11e6-9c70-b9373909deb8.png)
It cannot find the NODE_ENV value of development, even though development is the default value. Which is odd.
it doesn't seem to build the bundle.js either. 
I think the best option would be to run this in a linux vm using vagrant. Ill try it that way. 

Cheers for you help though.

UPDATE:

Well apparently wndows is case sensitive, i changed  `SET` to `set` for the start command, and it worked.

**Comment by GordyD** [comment]
Glad you found the solution to your problem.

With regards to the warning about the NODE_ENV value of `development` not matching any config files, that is because there is actually not one in the config/ folder currently, so it falls back to the default configuration.
