### ISSUE TITLE
Warning: React attempted to reuse markup in a container but the checksum was invalid

### ISSUE THREAD

**Issue by staticbuzz** [GordyD/3ree#49]
Totally new to this stack so forgive me if this is off base. I get this warning in dev console when loading the demo:
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting... and so on.
I did some research and found that if you wrap the <% {html} %> template in /server/views/index.ejs in an extra div, the issue goes away. The solution that gets rid of the warning for me looks like this:

`<div id="app"><div><%- html %></div></div>`

Awesome stack btw! Great work :)

**Comment by snobear** [comment]
@staticbuzz nice! Your solution worked for me. I looked into that error a bit and thought it was due to Redux dev tools adding some markup or something. It wasn't an issue in production so I ignored it.  Could you make a pull request to add this in?

**Comment by GordyD** [comment]
Have merged this issue. Thanks for raising @staticbuzz and thanks @snobear for responding to it so quickly. Appreciate the contributions!

**Comment by snobear** [comment]
This little fix significantly sped up the initial browser load time in dev for me.  Cheers to that!
