### ISSUE TITLE
Webpack Failing to Resolve

### ISSUE THREAD

**Issue by bsweaty** [GordyD/3ree#9]
![image](https://cloud.githubusercontent.com/assets/2700879/11049116/461e8dce-86f9-11e5-9974-cecbc92fbcd2.png)

getting an error resolving modules on install, any ideas?

n - 0.12.7

**Comment by loremipson** [comment]
+1 0.12.7 for me too.

**Comment by motebotic** [comment]
You can remove line 15 in webpack.config.js but you will lose hot reloading. I am new to webpack and just started playing around with it. Should be fun trying to work this out, ill update you guys if I figure it out ((:
`new webpack.HotModuleReplacementPlugin(),`
